### ISSUE TITLE
Para colocar as pastas , não pode ter repositório no github? 

### ISSUE THREAD

**Issue by JoaoPedro110** [Mayck-E/FreeCode#1]

**Comment by JoaoPedro110** [comment]
Mayck como sobe as pastas do git hub desktop para o git hub? 

Fica tranquilo que eu vou mudar mais coisas do seu codigo

**Comment by Mayck-E** [comment]
pode sim

**Comment by Mayck-E** [comment]
![image](https://user-images.githubusercontent.com/124847684/229122815-90897657-aaeb-4255-9414-2e9fc91bf367.png)

**Comment by JoaoPedro110** [comment]
é so colocar dentro da pasta

**Comment by JoaoPedro110** [comment]
mas não esta subindo para internet

**Comment by JoaoPedro110** [comment]
valeu mayck

Agora só vou ficar adicionando os negócios e atualizando o repositório
